app/assignments/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, IntegerField
from wtforms.validators import InputRequired, DataRequired, Length


class AssignmentFilter(FlaskForm):
    lower_bound = IntegerField("minimum difficulty: ")
    upper_bound = IntegerField("maximum difficulty: ")

app/assignments/views.py
from flask import Blueprint, redirect, render_template, flash, request
from flask.helpers import url_for
from flask_login import current_user, login_required
from app.assignments.forms import AssignmentFilter
from app.models import Assignment, Class, Teacher, Equation
from app import db

assignments = Blueprint('assignments', __name__, template_folder='templates')



@assignments.route('/add_assignment/<class_id>')
@login_required
def search_assignment(class_id):
    my_class = Class.query.get(class_id)
    equations = db.engine.execute('''
    SELECT eq.equation_id, eq.lhs as lhs, eq.rhs as rhs, ROUND(AVG(p.diff_rating), 2) as "difficulty"
    FROM equations as eq
    LEFT JOIN performances as p
    ON eq.equation_id = p.equation_id
    GROUP BY eq.equation_id
    ORDER BY "difficulty"''')
    form1 = AssignmentFilter()

    return render_template('search_assignments.html', my_class=my_class, form1=form1, equations=equations)


@assignments.route('/add_assignment/<class_id>/<equation_id>', methods=["GET", "POST"])
@login_required
def add_assignment(class_id, equation_id):
    teacher = Teacher.query.filter_by(user_id=current_user.user_id).first()
    if teacher:

        if request.method == "POST":
            date_time = request.form.get('due_date') + request.form.get('due_time')
            assign = Assignment(class_id, equation_id, date_time)
            db.session.add(assign)
            db.session.commit()
            flash("Assignment created")
            return redirect(url_for('assignments.search_assignment', class_id=class_id))
        
        my_class = Class.query.get(class_id)
        my_eq = Equation.query.get(equation_id)
        return render_template('add_assignment.html', my_equation=my_eq, my_class=my_class)
        
    else:
        flash("You do not have permission to view that page.")
        return redirect(url_for('main.home'))

app/assignments/templates/add_assignment.html
{% extends "base.html" %}

{% include "math_jax.html" %}

{% block title %}Create Assignment{% endblock %}

{% block content %}
    <main>
        <h6>Create assignment for {{ my_class.class_name }}</h6>
        <div class='shrink_eqs'>$${{ my_equation.lhs }}={{my_equation.rhs}}$$</div>
        <form method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <label for="due_date">Due Date: </label>
            <input type="date" id="due_date" name="due_date">
            <label for="due_time">Due at: </label>
            <input type="time" id="due_time" name="due_time">
            <input type="submit" value='Create Assignment'>
        </form>
    </main>


{% endblock %}

app/assignments/templates/search_assignments.html
{% extends "base.html" %}

{% include "math_jax.html" %}

{% block title %}Add Assignment{% endblock %}

{% block content %}
    <!-- <div>
        <h3>Add assignment for {{ my_class.class_name }}</h3>
        <form method="GET">
            {{ form1.csrf_token }}
            {{ form1.lower_bound.label }}
            {{ form1.lower_bound }}
            <br>
            {{ form1.upper_bound.label }}
            {{ form1.upper_bound }}
        </form>
    </div> -->
    <div>
        <a href="{{ url_for('equations.new_equation') }}">Have your own equation in mind? Click here!</a>
        <ul class="eq_list">
        {% for equation in equations %}
            <li>
                <div>$${{ equation.lhs }} = {{ equation.rhs }}$$</div><div>Difficulty:{{ equation.difficulty }}</div>
                <a href='{{ url_for("assignments.add_assignment", class_id=my_class.class_id, equation_id=equation.equation_id) }}'>Assign Equation</a>
            </li>
        {% endfor %}
        </ul>
    </div>



{% endblock %}