app/users/views.py
from flask import Blueprint, current_app, flash, redirect, render_template, url_for
from flask_login import current_user
from flask_login.utils import login_required
from sqlalchemy import desc
from app.models import Assignment, Student, Teacher, Performance
from app import db
from datetime import datetime

app = current_app
users = Blueprint('users', __name__, template_folder="templates")

def check_perfs(elem):
    student = Student.query.filter_by(user_id=current_user.user_id).first()
    return elem.student_id == student.student_id

@users.route('/profile')
@login_required
def profile():
    if current_user.role == 'student':
        student = Student.query.filter_by(user_id=current_user.user_id).first()
        if student.classroom:
            better_info = Assignment.query.filter(Assignment.class_id==student.class_id).order_by(desc(Assignment.due_date))
            my_student_perfs = []
            for assignment in better_info:
                perfs = filter(check_perfs,assignment.equation.performances)
                my_student_perfs.append(list(perfs))
            return render_template('profile.html', student=student, today=datetime.now, better_info=better_info, my_student_perfs=my_student_perfs)

        return render_template('profile.html', student=student)

    elif current_user.role == 'teacher':
        teacher = Teacher.query.filter_by(user_id=current_user.user_id).first()
        return render_template('profile.html', teacher=teacher)

@users.route('/stats/<user_id>')
@login_required
def stats(user_id):
    student = Student.query.filter_by(user_id=user_id).first()
    if current_user.role == 'student':
        if int(user_id) != current_user.user_id:
            flash("You are not authorized to view that information")
            return redirect(url_for("main.home"))
    elif current_user.role == 'teacher':
        teacher = Teacher.query.filter_by(user_id=current_user.user_id).first()
        if student.classroom not in teacher.classes:
            flash("You are not authorized to view that information")
            return redirect(url_for("main.home"))
    stats = db.engine.execute(f'''
    SELECT student_id, SUM(hints) as "total_hints",
    ROUND(AVG(hints),2) as "avg_hints", AVG(end_time - start_time) as "avg_time",
    ROUND(AVG(diff_rating),2) as "avg_diff_rating"
    FROM performances
    WHERE student_id={student.student_id}
    GROUP BY student_id;
    ''').first()
    avg_time = str(stats.avg_time)
    _, min, sec = avg_time.split(':')
    avg_time = f'{min} min {round(float(sec), 2)} sec'
    return render_template('stats.html', stats=stats, classroom=student.classroom, avg_time=avg_time)

app/users/templates/profile.html
{% extends "base.html" %}
{% from 'macros.html' import assignments_due %}
{% if current_user.role == 'student' %}
    {% include 'math_jax.html' %}
{% endif %}

{% block title %}{{ current_user.username }}'s Profile{% endblock %}

{% block content %}
    <div id="show_classes">
    {% if current_user.role == 'student' %}
        {% if student.classroom %}
            <h3>My Class: {{ student.classroom.class_name }}</h3><br>
            <h6>Assignments:</h6>
            <ul class="eq_list">
                {% for assignment in better_info %}
                    {% if my_student_perfs[loop.index0] %}
                        {{ assignments_due(assignment, 'past_due', 'Completed') }}
                    {% elif assignment.due_date < today() %}
                        {{ assignments_due(assignment, 'dead_due', 'Late') }}
                    {% else %}
                        {{ assignments_due(assignment, '', 'To-do') }}
                    {% endif %}
                {% endfor %}
            </ul>
            <a href="{{ url_for('users.stats', user_id=student.user_id) }}">View my stats</a>
        {% else %}
            <h6>You have not joined a class yet</h6>
            <a href="{{ url_for('classes.search') }}">Find your classroom</a>
        {% endif %}
    {% elif current_user.role == 'teacher' %}
        <h3>My Classes</h3><br>
        <a href="{{ url_for('classes.add_class', teacher_id=current_user._teach.teacher_id) }}">Create New Class</a>
        <ul>
            {% for my_class in teacher.classes %}
            <li><a href="{{ url_for('classes.view', class_id=my_class.class_id) }}">{{ my_class.class_name }}</a> | Students: {{ my_class.students|length }} | <a href="{{ url_for('assignments.search_assignment', class_id=my_class.class_id) }}">Add assignment</a></li>
            {% endfor %}
        </ul>

    {% endif %}
    </div>
{% endblock %}

app/users/templates/stats.html
{% extends "base.html" %}

{% block title %}{{ current_user.username }}'s stats{% endblock %}

{% block content %}
<main>
    <table>
        <tr><td>number of hints requested</td><td class='last'>{{ stats.total_hints }}</td></tr>
        <tr><td>number of hints requested per attempt</td><td class='last'>{{ stats.avg_hints }}</td></tr>
        <tr><td>average time of completion</td><td class='last'>{{ avg_time }}</td></tr>
        <tr><td>average diff rating</td><td class='last'>{{ stats.avg_diff_rating }}</td></tr>
    </table>
    {% if current_user.role == 'teacher' %}
        <a class='helplinks' href="{{ url_for('classes.view', class_id=classroom.class_id) }}">Return to class roster</a>
    {% endif %}
</main>


{% endblock %}